name: Main Workflow

on: [push]

jobs:
  build:
    name: Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose stack
        run: docker-compose up -d
      - name: Tests
        run: docker-compose exec web pytest
